file(READ ${GIT_COMMIT_ID_FILE} GIT_COMMIT_ID)
set(DOXY_PROJECT_NUMBER ${GIT_COMMIT_ID})
set(DOXY_STRIP_FROM_PATH ${${PROJECT_NAME}_GIT_REPO_ROOT})
configure_file(${DOXY_CONFIG_FILE_IN} ${DOXY_CONFIG_FILE} @ONLY)
