include(CheckParseArguments)

function(convert_bool_to_yes_no BOOL_VALUE)
    set(PREFIX ${CMAKE_CURRENT_FUNCTION})
    cmake_parse_arguments(${PREFIX} "" "OUTPUT_VARIABLE" "" ${ARGN})
    check_parse_arguments(${PREFIX})
    if (${BOOL_VALUE})
        set(OUTPUT_VALUE "YES")
    else()
        set(OUTPUT_VALUE "NO")
    endif()
    set(${${PREFIX}_OUTPUT_VARIABLE} ${OUTPUT_VALUE} PARENT_SCOPE)
endfunction()
